### ISSUE TITLE
Error handling for unsupported filetypes

### ISSUE THREAD

**Issue by shivupa** [dlf57/chemreps#6]
Currently the representations look for all files in a folder and assumes that they are all supported and attempts to load them. Clearly this could be an issue. 

The "loading" happens by making an instance of the molecule class. I think that the molecule class should return and error when passed an unsupported filetype and then we can catch this with a try/except.

**Comment by amandadumi** [comment]
I can make that happen this weekend. Will the handling be based on the file extension or file format?

**Comment by dlf57** [comment]
PR #11 fixed this so I am going to close it out
