### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by shivupa** [dlf57/chemreps#7]
Tests are important.

**Comment by dlf57** [comment]
I also think we should add codecov into our tests when we set that up

**Comment by amandadumi** [comment]
Needed Tests:

- molecule
    * build from xyz
    * build from sdf
    * build from file to raise exception
    * parse file from Gamess/Orca
- reps
    * a test for each rep

**Comment by amandadumi** [comment]
Hey guys, quick question. In regards to writing a test function for the bag of bonds array returned from the  bag of bonds function, I am simply storing the correct matrix for a given molecule. The pytest then asserts that the difference between the stored array and calculated array must be below a certain threshold. **What is an acceptable error threshold?** I was going with 1e-9, but I'm not sure if there is a standard here.

**Comment by shivupa** [comment]
That sounds good to me. If it gets it wrong it should be on the order of a whole number right?

**Comment by dlf57** [comment]
I would think it would be either a whole number or the first few decimal places. I would think 1e-9 would be fine.

**Comment by dlf57** [comment]
This will be closed now that tests were added with PR #32
